# Server Configuration
server.port=8000

server.address=0.0.0.0
# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

spring.data.mongodb.database=cafeteria_db

# JWT Configuration
app.jwtSecret=cafeteriaSecretKey
app.jwtExpirationInMs=86400000

# CORS Configuration
app.cors.allowedOrigins=*

# Logging Configuration
logging.level.com.cafeteria=DEBUG
logging.level.org.springframework.security=DEBUG

